# Generated by Django 4.0.2 on 2022-02-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_shipsarea_game_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipsarea',
            name='data',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
