# Generated by Django 4.0.2 on 2022-04-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_shipsarea_data_shipsarea_s_x1_shipsarea_s_x10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipsarea',
            name='sh_sum',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='shipsarea',
            name='shot_sum',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
